version: 1.0.{build}
image: Visual Studio 2017
configuration:
- FZDebug
- FZRetail
before_build:
  - nuget restore VS2017/Allegiance.sln
build:
  project: VS2017/Allegiance.sln
  parallel: true
  verbosity: minimal
