copy objs10\FZRetail\FedSrv\AllSrv.exe x86
copy objs10\FZRetail\FedSrv\AllSrv.PDB x86
copy objs10\FZRetail\AllSrvUI\AllSrvUI.exe x86 
copy objs10\FZRetail\AllSrvUI\AllSrvUI.PDB x86
copy objs10\FZRetail\Lobby\AllLobby.exe x86
copy objs10\FZRetail\Lobby\AllLobby.PDB x86
copy objs10\FZRetail\WinTrek\Allegiance.exe x86 
copy objs10\FZRetail\WinTrek\Allegiance.PDB x86
copy objs10\FZRetail\AGC\AGC.dll x86
copy objs10\FZRetail\AGC\AGC.PDB x86