//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AllSrvUI.rc
//
#define IDS_TITLE                       1
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ALLSRVUI_DIALOG             102
#define IDS_COLUMN_SENDER               102
#define IDD_GAME_NAME                   102
#define IDS_COLUMN_TARGET               103
#define IDS_COLUMN_MESSAGE              104
#define IDS_COLUMN_PLAYER               105
#define IDD_PAGE_CHAT                   106
#define IDS_COLUMN_TEAM                 106
#define IDD_PAGE_GAME_CREATE            107
#define IDS_COLUMN_SECTOR               107
#define IDS_AUTOUPDATE_NOW              108
#define IDS_AUTOUPDATE_NOW_KILLGAME     109
#define IDS_GAME_PARAMS                 111
#define IDS_BOOT_SELECTED_ONE           112
#define IDS_BOOT_SELECTED               113
#define IDS_STAGE_NONE                  114
#define IDS_STAGE_NOTSTARTED            115
#define IDS_STAGE_STARTING              116
#define IDS_STAGE_STARTED               117
#define IDS_STAGE_OVER                  118
#define IDS_STAGE_TERMINATE             119
#define IDS_DESTROY_ON_EXIT             120
#define IDS_PRODUCT_ID_NONE             121
#define IDS_LEGAL_WARNING               122
#define IDR_MAINFRAME                   128
#define IDD_CHAT_PREFERENCES            130
#define IDD_PAGE_PLAYERS                131
#define IDD_PAGE_DUMMY                  133
#define IDD_PAGE_CONNECT                134
#define IDD_GAME_SELECT                 135
#define IDD_TEAM_DYNAMICS               138
#define IDD_GAME_SPECIFICS              139
#define IDD_WINNING_CONDITIONS          140
#define IDB_ZONE                        145
#define IDI_CONQUEST                    146
#define IDI_COUNTDOWN                   147
#define IDI_DEATHMATCH                  148
#define IDI_PROSPERITY                  149
#define IDI_ARTIFACTRUN                 150
#define IDI_FLAGS                       151
#define IDI_INBALANCE                   159
#define IDI_MINTEAM                     160
#define IDI_MAXTEAM                     161
#define IDI_TEAMCOUNT                   162
#define IDI_SKILL                       163
#define IDI_LIVES                       164
#define IDI_TOTAL_MONEY                 165
#define IDI_START_MONEY                 166
#define IDC_PRIVATE_GAME                1000
#define IDC_PUBLIC_GAME                 1001
#define IDC_GAME_NAME                   1004
#define IDC_GAME_PASSWORD               1005
#define IDC_GAME_SETTINGS               1006
#define IDC_GAME_CREATE                 1007
#define IDC_GAME_DESTROY                1008
#define IDC_LOBBY_SERVER_CAPTION        1009
#define IDC_GAME_SELECT                 1009
#define IDC_GAME_NAME_CAPTION           1010
#define IDC_GAME_PASSWORD_CAPTION       1011
#define IDC_LOBBY_SERVER                1012
#define IDC_GAME_CORE                   1012
#define IDC_GAME_CORE_CAPTION           1013
#define IDC_CHAT_PREFERENCES            1015
#define IDC_CHAT_LIST                   1016
#define IDC_SEND_CHAT_TEXT              1017
#define IDC_SEND_CHAT                   1018
#define IDC_SEND_CHAT_CAPTION           1019
#define IDC_UNLIMITED_CHAT_HISTORY      1020
#define IDC_LIMIT_CHAT_HISTORY          1021
#define IDC_CHAT_HISTORY_LIMIT          1022
#define IDC_ADMIN_MSGBOX                1026
#define IDC_ADMIN_RUN                   1027
#define IDC_MISSION_NAME                1031
#define IDC_PASSWORD                    1032
#define IDC_CHAT_LIST_CLEAR             1033
#define IDC_ADMIN_RUN_PROPERTIES        1034
#define IDC_ADMIN_CHAT_LIST             1035
#define IDC_ENABLE_CHAT_LIST            1036
#define IDC_SKILL_LEVEL                 1036
#define IDC_LIMIT_POST_CAPTION          1037
#define IDC_STATS_COUNT                 1037
#define IDC_TEAM_LIVES                  1037
#define IDC_ADMIN_RUN_TEST              1038
#define IDC_MISSION_NAME_CAPTION        1038
#define IDC_ALLOW_DEFECTIONS            1038
#define IDC_ALLOW_JOINERS               1039
#define IDC_STARTING_MONEY              1039
#define IDC_PROGRESS_CONNECTING         1040
#define IDC_SQUAD_GAME                  1040
#define IDC_TOTAL_MONEY                 1040
#define IDC_PASSWORD_CAPTION            1041
#define IDC_EJECT_PODS                  1041
#define IDC_BOOT_PLAYERS                1042
#define IDC_ALLOW_FRIENDLY_FIRE         1042
#define IDC_PLAYER_LIST                 1043
#define IDC_INVULNERABLE_STATIONS       1043
#define IDC_MAX_TEAM_INBALANCE          1043
#define IDC_DEVELOPMENT                 1044
#define IDC_MIN_TEAM_PLAYERS            1044
#define IDC_GAME_VISIBILITY             1044
#define IDC_REVEAL_MAP                  1045
#define IDC_MAX_TEAM_PLAYERS            1045
#define IDC_GAME_SETTINGS_CAPTION       1045
#define IDC_TEAM_COUNT                  1046
#define IDC_MAX_PLAYERS                 1046
#define IDC_MAX_PLAYERS_CAPTION         1047
#define IDC_RESOURCES                   1048
#define IDC_PROGRESS_CONNECTING_CAPTION 1048
#define IDC_MAP_TYPE                    1049
#define IDC_PROGRESS_CONNECTING_GROUP   1049
#define IDC_GAME_TYPE                   1050
#define IDC_FLAGS                       1051
#define IDC_GAME_LIST                   1051
#define IDC_COUNTDOWN                   1052
#define IDC_LOCK_GAME_OPEN              1052
#define IDC_CONQUEST                    1053
#define IDC_SEND_CHAT_ALL_GAMES         1053
#define IDC_PROSPERITY                  1054
#define IDC_LEGAL                       1054
#define IDC_REQUIRED_KILLS              1055
#define IDC_DESCRIPTION                 1055
#define IDC_VERSION                     1056
#define IDC_ARTIFACT_RUNS               1057
#define IDC_COPYRIGHT                   1057
#define IDC_PRODUCT_ID                  1058
#define IDC_LEGAL_WARNING               1059
#define IDC_CHECK1                      1060
#define IDC_AET                         1060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
