//<Djole  date="2015-03-24">
#ifndef ALLEGCONFIG_H
#define ALLEGCONFIG_H

#define ALLEG_GFX_DEFAULT_WIDTH 800
#define ALLEG_GFX_DEFAULT_HEIGHT 600
#define ALLEG_GFX_COMBAT_WIDTH 1024
#define ALLEG_GFX_COMBAT_HEIGHT 768


#endif /*ALLEGCONFIG_H*/
//</Djole>