;// Comment Field
LanguageNames=(English=0x409:FEDMSG)
MessageId=0
SymbolicName=SRVDBG_ASSERT
Language=English
Allegiance Assert from %1:%n%n%2%n%3%n%n%4%5
.
MessageId=1
SymbolicName=SRVDBG_EXCEPTION
Language=English
Allegiance Exception from %1:%n%n%2%n%n%3%4
.
MessageId=2
SymbolicName=SRVDBG_ABORT
Language=English
Allegiance Abort from %1:%n%n%2%n%n%3%4
.
MessageId=3
SymbolicName=SRVDBG_NOTIFYABORT
Language=English
Allegiance NotifyAbort from %1:%n%n%2%n%n%3%4
.
MessageId=1000
SymbolicName=SRVDBG_ERROR
Language=English
Allegiance Error from %1:%n%n%2%n%3%n%n%4%5
.
MessageId=2000
SymbolicName=SRVDBG_WARNING
Language=English
Allegiance Warning from %1:%n%n%2%n%3%n%n%4%5
.
MessageId=3000
SymbolicName=SRVDBG_INFO
Language=English
Allegiance Information from %1:%n%n%2%n%3%n%n%4%5
.
MessageId=1002
SymbolicName=SRVDBG_CANTCREATEARTMONITOR
Language=English
Allegiance Information from %1:%nArt File Not Found%n%2%n%3%n%4
.
MessageId=3001
SymbolicName=SRVDBG_ARTFILESCHANGED
Language=English
Allegiance Information from %1:%nArt Change Monitor Creation%n%2%n%3%n%4
.
