copy %1\Accel.wav			    %2
copy %1\aft.bmp				    %2
copy %1\arrows.bmp			    %2
copy %1\direction.bmp		    %2
copy %1\Ef03.wav			    %2
copy %1\Ef10.wav			    %2
copy %1\ef21.wav			    %2
copy %1\Ef29.wav			    %2
copy %1\Ef51a.wav			    %2
copy %1\Ef86.wav			    %2
copy %1\Ef88.wav			    %2
copy %1\Ef89.wav			    %2
copy %1\ef51a.wav			    %2
copy %1\ef121.wav			    %2
copy %1\ef120.wav			    %2
copy %1\exp20.bmp			    %2
copy %1\exp22.bmp			    %2
copy %1\exp23.bmp			    %2
copy %1\exp24.bmp			    %2
copy %1\fore.bmp			    %2
copy %1\F13.bmp			    %2
copy %1\FX09.bmp			    %2
copy %1\hitsIndicator.bmp	    %2
copy %1\intro.wav			    %2
copy %1\lead.bmp			    %2
copy %1\Markers.bmp			    %2
copy %1\mis11.bmp			    %2
copy %1\music3.wav			    %2
copy %1\ShieldHull.bmp		    %2
copy %1\shieldsIndicator.bmp    %2
copy %1\shipInt.wav			    %2
copy %1\shipOut.wav			    %2
copy %1\music3.wav			    %2
copy %1\lifeover.wav			    %2
copy %1\jumpin.wav			    %2
copy %1\ef23.wav			    %2
copy %1\ef24.wav			    %2
copy %1\title.bmp			    %2
copy %1\xhair.bmp			    %2
copy %1\nosearthead.bmp			%2
copy %1\wingarthead.bmp			%2
copy %1\tailart.bmp			%2
copy %1\noseart.bmp			%2
copy %1\wingart.bmp			%2
copy %1\tailarthead.bmp			%2
copy %1\title.bmp			%2
copy %1\loadout.bmp			%2
copy %1\ships.bmp			%2
copy %1\shipshead.bmp			%2
copy %1\weapons.bmp			%2
copy %1\weaponsHead1.bmp			%2
copy %1\weaponsHead2.bmp			%2
copy %1\weaponsHead3.bmp			%2
copy %1\weaponsHead4.bmp			%2
copy %1\weaponsHead5.bmp			%2
copy %1\weaponsHead6.bmp			%2
copy %1\weaponsHead7.bmp			%2
copy %1\weaponsHead8.bmp			%2
copy %1\cammohead.bmp			%2
copy %1\colorcam.bmp			%2
copy %1\colorhead.bmp                   %2

copy %1\energyGrid.bmp                   %2
copy %1\shield.bmp                   %2
copy %1\hull.bmp                   %2

copy %1\VGauge.bmp                      %2
copy %1\DamageGauge.bmp                 %2
copy %1\UpPointer.bmp                   %2
copy %1\DownPointer.bmp                 %2
copy %1\LeftPointer.bmp                 %2
copy %1\Ruler.bmp                       %2
copy %1\DirectionNew.bmp                %2
copy %1\Lead.bmp                        %2

copy %1\ordered.BMP                     %2
copy %1\Targeted.BMP                    %2
copy %1\Gauge1.BMP                     %2
copy %1\Gauge2.BMP                     %2
copy %1\Gauge3.BMP                     %2
copy %1\Gauge4.BMP                     %2
copy %1\Gauge5.BMP                     %2
copy %1\Gauge6.BMP                     %2
copy %1\Gauge7.BMP                     %2
copy %1\Gauge8.BMP                     %2
copy %1\Gauge9.BMP                     %2
copy %1\Gauge10.BMP                     %2
copy %1\lastfired.BMP                   %2
copy %1\Friendly.BMP                    %2
copy %1\Planet.BMP                    %2
copy %1\Fighter.BMP                    %2
copy %1\Capitol.BMP                    %2
copy %1\Aleph.BMP                    %2
copy %1\Missle.BMP                    %2
copy %1\Station.BMP                    %2

copy %1\hudbkgrnd.bmp                    %2
copy %1\mount.bmp                    %2
copy %1\nomount.bmp                    %2
copy %1\nodrop.bmp                    %2
copy %1\grid.bmp                    %2
copy %1\inrange.bmp                    %2
copy %1\speedindicator.bmp                    %2
copy %1\landingear.bmp                    %2
copy %1\noreplace.bmp                    %2

copy %1\afterburner.bmp          %2
copy %1\alephicon.bmp          %2
copy %1\belorian.bmp          %2
copy %1\clanyuzell.bmp          %2
copy %1\crimson.bmp          %2

copy %1\equipment.bmp          %2
copy %1\fuelcan.bmp          %2
copy %1\gunicon.bmp          %2
copy %1\housebrmn.bmp          %2
copy %1\ironleague.bmp          %2
copy %1\meteoricon.bmp          %2
copy %1\moneybag.bmp          %2
copy %1\planeticon.bmp          %2
copy %1\rixian.bmp          %2

copy %1\weapon.bmp          %2
copy %1\locked.bmp          %2
copy %1\plock.bmp          %2
