delete from Ranks where CivID=1
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(0, 1,0, 'Podling')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(1, 1,500, 'Tadpole')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(2, 1,2000, 'Citizen')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(3, 1,5000, 'Auxiliary')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(4, 1,9000, 'Legionary')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(5, 1,14000, 'Optio')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(6, 1,20000, 'Decurion')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(7, 1,26000, 'Centurion')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(8, 1,34000, 'Legion Commander')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(9, 1,43000, 'Tribune')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(10, 1,54000, 'Legate')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(11, 1,65000, 'Count')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(12, 1,77000, 'Duke')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(13, 1,90000, 'Overlord')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(14, 1,105000, 'Imperator ')
delete from Ranks where CivID=2
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(0, 2,0, 'Bit')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(1, 2,500, 'Byte')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(2, 2,2000, 'Word')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(3, 2,5000, 'Register')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(4, 2,9000, 'Index')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(5, 2,14000, 'Variable')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(6, 2,20000, 'Subroutine')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(7, 2,26000, 'Program')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(8, 2,34000, 'Utility')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(9, 2,43000, 'Application')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(10, 2,54000, 'Compiler')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(11, 2,65000, 'Driver')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(12, 2,77000, 'Daemon')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(13, 2,90000, 'Kernel')
INSERT INTO [Federation].[dbo].[Ranks]([Rank], [CivID], [Requirement], [Name]) VALUES(14, 2,105000, 'OS')
