/*
**  Copyright (C) 1996, 1997 Microsoft Corporation. All Rights Reserved.
**
**  File:       pch.h
**
**  Author: 
**
**  Description:
**      Standard header, generated by the ATL wizard and used to define a
**  precompiled header that contains everything common to all files.
**
**  History:
*/

#define __MODULE__ "igc"

//
// Windows headers
//

#include "windows.h"
#include <mmsystem.h>

//
// Wintrek headers
//

#include "guids.h"
#include "zlib.h"
#include "utility.h"
#include "igc.h"

#include "private.h"

// BT - STEAM
#include "AllegianceSecurity.h"
