/*
 *	buildConfig.h -- Build configuration file.
 *
 *	WARNING: DO NOT EDIT. This file is generated by configure.
 *
 *	Use "./configure --help" to learn how to use the configure script to
 *	customize the configuration.
 */

 #ifdef BLD_ALTERNATE_CONFIG
 #include BLD_ALTERNATE_CONFIG
 #else
#define BLD_PRODUCT "appweb"
#define BLD_NAME "Mbedthis Appweb"
#define BLD_VERSION "2.4.2"
#define BLD_NUMBER "2"
#define BLD_TYPE "RELEASE"
#define BLD_DEFAULTS "standard"
#define BLD_PACKAGES ""
#define BLD_MBEDTHIS 1
#define BLD_REQUIRED_TOOLS "AR CC CXX LD LDXX"
#define BLD_OPTIONAL_TOOLS ""
#define BLD_REQUIRED_SDKS ""
#define BLD_OPTIONAL_SDKS ""
#define BLD_REQUIRED_BUILD_TOOLS "AR CC CXX LD LDXX"
#define BLD_OPTIONAL_BUILD_TOOLS "DOXYGEN PKG"
#define BLD_REQUIRED_BUILD_SDKS ""
#define BLD_OPTIONAL_BUILD_SDKS ""
#define BLD_COMPANY "Mbedthis"
#define BLD_DEBUG 0
#define BLD_DIRS "tools include obj lib bin mpr ejs esp http doc appweb samples package releases"
#define BLD_CLEAN_INSTALL "0"
#define BLD_LICENSE "gpl"
#define BLD_COMMERCIAL "0"
#define BLD_HOST_SYSTEM "x86_64-pc-win"
#define BLD_BUILD_SYSTEM "i686-pc-win"
#define BLD_CROSS "1"
#define BLD_HOST_OS "WIN"
#define BLD_HOST_CPU_ARCH MPR_CPU_IX64
#define BLD_HOST_CPU "x86_64"
#define BLD_HOST_CPU_UPPER "X86_64"
#define BLD_HOST_CPU_MODEL "86_64"
#define BLD_HOST_DIST "xp"
#define BLD_HOST_DIST_VER "5"
#define BLD_HOST_UNIX 0
#define BLD_HOST_WIN 1
#define BLD_BUILD_OS "WIN"
#define BLD_BUILD_CPU_ARCH MPR_CPU_IX86
#define BLD_BUILD_CPU i686
#define BLD_BUILD_CPU_UPPER I686
#define BLD_BUILD_CPU_MODEL 686
#define BLD_BUILD_UNIX 0
#define BLD_BUILD_WIN 1
#define BLD_ROOT_PREFIX "E:/cygwin"
#define BLD_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb"
#define BLD_DOC_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb"
#define BLD_INC_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/include/appweb"
#define BLD_LIB_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/lib"
#define BLD_LOG_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/logs"
#define BLD_MAN_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb"
#define BLD_SAM_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/samples"
#define BLD_SBIN_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/bin"
#define BLD_SRC_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/src"
#define BLD_HOST_CC_MTUNE 0
#define BLD_HOST_CC_STACK_PROTECTOR 0
#define BLD_HOST_CC_MSCL 0
#define BLD_HOST_CC_CL_VERSION 12
#define BLD_BUILD_CC_MTUNE 0
#define BLD_BUILD_CC_STACK_PROTECTOR 0
#define BLD_BUILD_CC_MSCL 0
#define BLD_BUILD_CC_CL_VERSION 12
#define BLD_MOD_PREFIX "E:/cygwin/Program Files/Mbedthis Appweb/lib/modules"
#define BLD_WEB_PREFIX "E:/cygwin/appweb/web"
#define BLD_APPWEB 1
#define BLD_HTTP_PORT 7777
#define BLD_SSL_PORT 4443
#define BLD_APPWEB_CONFIG "standard.conf"
#define BLD_FEATURE_ACCESS_LOG 1
#define BLD_FEATURE_ADMIN_MODULE 0
#define BLD_FEATURE_ASPNET_MODULE 0
#define BLD_FEATURE_ASSERT 0
#define BLD_FEATURE_AUTH_MODULE 0
#define BLD_FEATURE_C_API_MODULE 0
#define BLD_FEATURE_C_API_CLIENT 1
#define BLD_FEATURE_CGI_MODULE 0
#define BLD_FEATURE_DIR_MODULE 0
#define BLD_FEATURE_DOC 0
#define BLD_FEATURE_CMD_EXEC 1
#define BLD_FEATURE_GACOMPAT_MODULE 0
#define BLD_FEATURE_CONFIG_PARSE 1
#define BLD_FEATURE_CONFIG_SAVE 0
#define BLD_FEATURE_COOKIE 1
#define BLD_FEATURE_COPY_MODULE 0
#define BLD_FEATURE_DIGEST 1
#define BLD_FEATURE_EGI_MODULE 0
#define BLD_FEATURE_EJS 1
#define BLD_FEATURE_ESP_MODULE 0
#define BLD_FEATURE_EVAL_PERIOD 30
#define BLD_FEATURE_FLOATING_POINT 1
#define BLD_FEATURE_IF_MODIFIED 1
#define BLD_FEATURE_IPV6 0
#define BLD_FEATURE_KEEP_ALIVE 1
#define BLD_FEATURE_LEGACY_API 0
#define BLD_FEATURE_LICENSE 0
#define BLD_FEATURE_LOG 1
#define BLD_FEATURE_DLL 1
#define BLD_FEATURE_MULTITHREAD 1
#define BLD_FEATURE_NUM_TYPE int
#define BLD_FEATURE_NUM_TYPE_ID MPR_TYPE_INT
#define BLD_FEATURE_STDCPP 1
#define BLD_FEATURE_PUT_MODULE 0
#define BLD_FEATURE_RANGES 1
#define BLD_FEATURE_ROMFS 0
#define BLD_FEATURE_RUN_AS_SERVICE 1
#define BLD_FEATURE_SAFE_STRINGS 0
#define BLD_FEATURE_SAMPLES 1
#define BLD_FEATURE_SESSION 1
#define BLD_FEATURE_SHARED 0
#define BLD_FEATURE_SQUEEZE 0
#define BLD_FEATURE_SSL_MODULE 0
#define BLD_FEATURE_STATIC 1
#define BLD_FEATURE_STATIC_LINK_LIBC 0
#define BLD_FEATURE_TEST 0
#define BLD_FEATURE_UPLOAD_MODULE 0
#define BLD_FEATURE_SERVICES 1
#define BLD_FEATURE_ADMIN_MODULE_BUILTIN 1
#define BLD_FEATURE_ASPNET_MODULE_BUILTIN 0
#define BLD_FEATURE_AUTH_MODULE_BUILTIN 1
#define BLD_FEATURE_C_API_MODULE_BUILTIN 1
#define BLD_FEATURE_CGI_MODULE_BUILTIN 1
#define BLD_FEATURE_DIR_MODULE_BUILTIN 1
#define BLD_FEATURE_GACOMPAT_MODULE_BUILTIN 0
#define BLD_FEATURE_COPY_MODULE_BUILTIN 1
#define BLD_FEATURE_EGI_MODULE_BUILTIN 1
#define BLD_FEATURE_ESP_MODULE_BUILTIN 1
#define BLD_FEATURE_SSL_MODULE_BUILTIN 1
#define BLD_FEATURE_PUT_MODULE_BUILTIN 1
#define BLD_FEATURE_UPLOAD_MODULE_BUILTIN 1
#define BLD_FEATURE_ADMIN_MODULE_LOADABLE 0
#define BLD_FEATURE_ASPNET_MODULE_LOADABLE 0
#define BLD_FEATURE_AUTH_MODULE_LOADABLE 0
#define BLD_FEATURE_C_API_MODULE_LOADABLE 0
#define BLD_FEATURE_CGI_MODULE_LOADABLE 0
#define BLD_FEATURE_DIR_MODULE_LOADABLE 0
#define BLD_FEATURE_GACOMPAT_MODULE_LOADABLE 0
#define BLD_FEATURE_COPY_MODULE_LOADABLE 0
#define BLD_FEATURE_EGI_MODULE_LOADABLE 0
#define BLD_FEATURE_ESP_MODULE_LOADABLE 0
#define BLD_FEATURE_SSL_MODULE_LOADABLE 0
#define BLD_FEATURE_PUT_MODULE_LOADABLE 0
#define BLD_FEATURE_UPLOAD_MODULE_LOADABLE 0
#define BLD_MOD_DIR "${BLD_TOP}/lib/modules"
#define BLD_HOST_AR "/cygdrive/G/VS10/VC/bin/lib"
#define BLD_HOST_AR_DOSPATH "G:/VS10/VC/bin/lib"
#define BLD_HOST_CC "/cygdrive/G/VS10/VC/bin/cl"
#define BLD_HOST_CC_DOSPATH "G:/VS10/VC/bin/cl"
#define BLD_HOST_CXX "/cygdrive/G/VS10/VC/bin/cl"
#define BLD_HOST_CXX_DOSPATH "G:/VS10/VC/bin/cl"
#define BLD_HOST_LD "/cygdrive/G/VS10/VC/bin/link"
#define BLD_HOST_LD_DOSPATH "G:/VS10/VC/bin/link"
#define BLD_HOST_LDXX "/cygdrive/G/VS10/VC/bin/link"
#define BLD_HOST_LDXX_DOSPATH "G:/VS10/VC/bin/link"
#define BLD_BUILD_AR "/cygdrive/G/VS10/VC/bin/lib"
#define BLD_BUILD_AR_DOSPATH "G:/VS10/VC/bin/lib"
#define BLD_BUILD_CC "/cygdrive/G/VS10/VC/bin/cl"
#define BLD_BUILD_CC_DOSPATH "G:/VS10/VC/bin/cl"
#define BLD_BUILD_CXX "/cygdrive/G/VS10/VC/bin/cl"
#define BLD_BUILD_CXX_DOSPATH "G:/VS10/VC/bin/cl"
#define BLD_BUILD_LD "/cygdrive/G/VS10/VC/bin/link"
#define BLD_BUILD_LD_DOSPATH "G:/VS10/VC/bin/link"
#define BLD_BUILD_LDXX "/cygdrive/G/VS10/VC/bin/link"
#define BLD_BUILD_LDXX_DOSPATH "G:/VS10/VC/bin/link"
#define BLD_BUILD_DOXYGEN ""
#define BLD_BUILD_DOXYGEN_DOSPATH ""
#define BLD_BUILD_PKG ""
#define BLD_BUILD_PKG_DOSPATH ""
#define BLD_BUILD_CFLAGS ""
#define BLD_HOST_CFLAGS ""
#define BLD_BUILD_CXXFLAGS ""
#define BLD_HOST_CXXFLAGS ""
#define BLD_BUILD_IFLAGS ""
#define BLD_HOST_IFLAGS ""
#define BLD_BUILD_LDFLAGS ""
#define BLD_HOST_LDFLAGS ""
#define BLD_BUILD_LDXXFLAGS ""
#define BLD_HOST_LDXXFLAGS ""
#define BLD_BUILD_JFLAGS ""
#define BLD_HOST_JFLAGS ""
#define BLD_BUILD_ARCH ".lib"
#define BLD_BUILD_EXE ".exe"
#define BLD_BUILD_OBJ ".obj"
#define BLD_BUILD_PIOBJ ".obj"
#define BLD_BUILD_CLASS ".class"
#define BLD_BUILD_SHLIB ".lib"
#define BLD_BUILD_SHOBJ ".dll"
#define BLD_HOST_ARCH ".lib"
#define BLD_HOST_EXE ".exe"
#define BLD_HOST_OBJ ".obj"
#define BLD_HOST_PIOBJ ""
#define BLD_HOST_CLASS ".class"
#define BLD_HOST_SHLIB ".lib"
#define BLD_HOST_SHOBJ ".dll"
#define BLD_TOOLS_DIR "${BLD_TOP}/tools"
#define BLD_BIN_DIR "${BLD_TOP}/bin"
#define BLD_LIB_DIR "${BLD_TOP}/lib"
#define BLD_INC_DIR "${BLD_TOP}/include"
#define BLD_EXP_OBJ_DIR "${BLD_TOP}/obj"

#endif /* BLD_ALTERNATE_CONFIG */
